@Library('deploy-conf')_
node() {
    try {
        String ANSI_GREEN = "\u001B[32m"
        String ANSI_NORMAL = "\u001B[0m"
        String ANSI_BOLD = "\u001B[1m"
        String ANSI_RED = "\u001B[31m"
        String ANSI_YELLOW = "\u001B[33m"

         ansiColor('xterm') {
              stage('Checkout') {
                cleanWs()
                checkout scm
                commit_hash = sh(script: 'git rev-parse --short HEAD', returnStdout: true).trim()
                build_tag = sh(script: "echo " + params.github_release_tag.split('/')[-1] + "_" + commit_hash + "_" + env.BUILD_NUMBER, returnStdout: true).trim()
                echo "build_tag: " + build_tag
             }
         }

        stage('Build') {
            sh """
                 cd lms_service_api_test
                 ls
                 mvn -X clean verify
              """
        }

    } catch (err) {
        currentBuild.result = "FAILURE"
        throw err
    } finally {
        archiveArtifacts 'lms_service_api_test/target/target/citrus-reports/citrus-test-results.html'
    }
}